GET inaltera-api-rest-production.up.railway.app/users HTTP/1.1

###

GET http://localhost:3000/users/2 HTTP/1.1

###

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "Email": "manolo@example.com",
    "Password": "patata123",
    "Nombre": "Roberto Linares"
}

###

PUT http://localhost:3000/users/4 HTTP/1.1
Content-Type: application/json

{
    "name": "Rosa Melano"
}

###

DELETE http://localhost:3000/users/4 HTTP/1.1